Update build.ps1 to support version 1.0.0
cake-build/example pull request #57
Opened 2021-02-09 23:00 UTC by EdgardosReis

based on documentation here https://cakebuild.net/docs/running-builds/runners/cake-runner-for-dotnet-framework#switches
changed also the other switches to "--". Not sure what to do with the -configuration, -experimental and -mono. Didn't change for now. tell me if this should be changed too.

2021-02-09 23:05 UTC, devlead commented
You could probably take the bootstrappers from
https://www.github.com/cake-build/resources/tree/master/dotnet-framework

Mono and experimental no longer a thing, so those aren't needed in build.ps1/sh.

2021-02-09 23:08 UTC, augustoproiete requested changes
UPDATE: nevermind, I see @devlead's comment about the bootstrappers not using this anymore.

Thanks for the PR @EdgardosReis!

With Cake v1.0 all input arguments must now use one `-` when passing a single character argument, and two `--` when using an argument that has multiple characters~, so both `-configuration` and `-experimental` need to be updated as well~

2021-02-09 23:08 UTC, augustoproiete commented on build.ps1
>  if ($Experimental) { $cakeArguments += "-experimental" }
```suggestion
if ($Experimental) { $cakeArguments += "--experimental" }
```

2021-02-09 23:08 UTC, augustoproiete commented on build.ps1
>  if ($Configuration) { $cakeArguments += "-configuration=$Configuration" }
```suggestion
if ($Configuration) { $cakeArguments += "--configuration=$Configuration" }
```

2021-02-09 23:09 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/cake-build/example?pullRequest=57) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/example?pullRequest=57) before we can accept your contribution.<br/><br/>:x: EdgardosReis [sign now](https://cla.dotnetfoundation.org/cake-build/example?pullRequest=57)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/example?pullRequest=57) it.</sub>

2021-02-10 05:16 UTC, devlead approved these changes
LGTM 👍

2021-02-10 05:16 UTC, merged

2021-02-10 05:17 UTC, devlead commented
@EdgardosReis your changes have been merged, thanks for your contribution 👍